export const DEFAULT_DATA = {
  tripTitle: "우리끼리 리트릿",
  tagline: "A quiet weekend away",
  startDate: "",
  endDate: "",
  participants: [
    { id: 1, name: "", role: "호스트", phone: "", note: "" },
    { id: 2, name: "", role: "총무", phone: "", note: "" },
    { id: 3, name: "", role: "요리", phone: "", note: "" },
    { id: 4, name: "", role: "사진", phone: "", note: "" },
    { id: 5, name: "", role: "플레이리스트", phone: "", note: "" },
    { id: 6, name: "", role: "참가자", phone: "", note: "" },
    { id: 7, name: "", role: "참가자", phone: "", note: "" },
    { id: 8, name: "", role: "참가자", phone: "", note: "" },
  ],
  schedule: {
    day1: [
      { id: 11, time: "15:00", activity: "체크인 · 짐 풀기", leader: "", linkedPlaceId: null },
      { id: 12, time: "16:00", activity: "동네 산책 · 마트 장보기", leader: "", linkedPlaceId: null },
      { id: 13, time: "18:30", activity: "바베큐 저녁", leader: "", linkedPlaceId: null },
      { id: 14, time: "21:00", activity: "보드게임 · 수다 타임", leader: "", linkedPlaceId: null },
      { id: 15, time: "23:30", activity: "야식 · 와인 한 잔", leader: "", linkedPlaceId: null },
      { id: 16, time: "01:30", activity: "취침", leader: "", linkedPlaceId: null },
    ],
    day2: [
      { id: 21, time: "09:30", activity: "늦은 기상 · 커피", leader: "", linkedPlaceId: null },
      { id: 22, time: "10:30", activity: "브런치", leader: "", linkedPlaceId: null },
      { id: 23, time: "12:00", activity: "팔당호 드라이브 · 카페", leader: "", linkedPlaceId: null },
      { id: 24, time: "14:00", activity: "점심 (근처 맛집)", leader: "", linkedPlaceId: null },
      { id: 25, time: "16:00", activity: "숙소 정리", leader: "", linkedPlaceId: null },
      { id: 26, time: "17:00", activity: "해산", leader: "", linkedPlaceId: null },
    ],
  },
  packingGroup: [
    { id: 101, name: "블루투스 스피커", assignee: "", checked: false },
    { id: 102, name: "보드게임", assignee: "", checked: false },
    { id: 103, name: "인스탁스 / 필름 카메라", assignee: "", checked: false },
    { id: 104, name: "고기 · 식재료", assignee: "", checked: false },
    { id: 105, name: "와인 · 맥주", assignee: "", checked: false },
    { id: 106, name: "간식 · 안주", assignee: "", checked: false },
    { id: 107, name: "멀티탭 · 일회용품", assignee: "", checked: false },
    { id: 108, name: "쓰레기봉투 · 분리수거 봉투", assignee: "", checked: false },
  ],
  packingPersonal: [
    { id: 201, name: "세면도구 · 수건", checked: false },
    { id: 202, name: "실내복 · 잠옷", checked: false },
    { id: 203, name: "갈아입을 옷", checked: false },
    { id: 204, name: "편한 운동화", checked: false },
    { id: 205, name: "충전기 · 보조배터리", checked: false },
    { id: 206, name: "마스크팩 · 스킨케어", checked: false },
    { id: 207, name: "가벼운 외투 (밤엔 쌀쌀)", checked: false },
    { id: 208, name: "슬리퍼", checked: false },
  ],
  meals: [
    { id: 301, when: "DAY 1 · 저녁", menu: "바베큐", chef: "", note: "삼겹살, 목살, 쌈채소, 버섯, 공깃밥" },
    { id: 302, when: "DAY 1 · 야식", menu: "라면 & 치즈", chef: "", note: "가볍게" },
    { id: 303, when: "DAY 2 · 브런치", menu: "토스트 & 커피", chef: "", note: "에그, 아보카도 등" },
    { id: 304, when: "DAY 2 · 점심", menu: "근처 맛집", chef: "외식", note: "식당 탭에서 확정" },
  ],
  places: { food: [], cafe: [], play: [] },
  expenses: [
    { id: 401, item: "숙소비", amount: 0, payer: "" },
    { id: 402, item: "마트 장보기", amount: 0, payer: "" },
    { id: 403, item: "주류 · 간식", amount: 0, payer: "" },
  ],
  feePerPerson: 50000,
  planHeadline: "낮엔 호숫가,\n밤엔 우리들의 거실.",
  planItems: [
    "체크인 후 동네 한 바퀴. 마트에 들러 저녁거리를 산다.",
    "마당에서 바베큐. 해가 완전히 지기 전에 불을 피운다.",
    "밤엔 보드게임이나 영화. 누가 먼저 잠드는지 시합.",
    "늦게 일어나 커피. 팔당호 드라이브와 카페 투어.",
    "정오의 맛집 한 곳을 정하고, 배부르게 먹고 해산.",
  ],
};
